const newproductsData = [
  {
    id: 0,
    image: "/newproducts/product1.png",
    title: "Breed Dry Dog Food",
    price: 40,
    originalPrice: 360,
    rating: 4,
    reviews: 65,
  },
  {
    id: 1,
    image: "/newproducts/product2.png",
    title: "CANON EOS DSLR Camera",
    price: 560,
    originalPrice: 1160,
    rating: 5,
    reviews: 589,
  },
  {
    id: 2,
    image: "/newproducts/product3.png",
    title: "ASUS FHD Gaming Laptop",
    price: 1200,
    originalPrice: 170,
    rating: 1,
    reviews: 10,
  },
  {
    id: 3,
    image: "/newproducts/product4.png",
    title: "Curology Product Set",
    price: 20,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
  {
    id: 4,
    image: "/newproducts/product5.png",
    title: "Kids Electric Car",
    price: 80,
    originalPrice: 360,
    rating: 4,
    reviews: 65,
  },
  {
    id: 5,
    image: "/newproducts/product6.png",
    title: "Soccer Cleats",
    price: 10,
    originalPrice: 1160,
    rating: 5,
    reviews: 589,
  },
  {
    id: 6,
    image: "/newproducts/product7.png",
    title: "GP11 Shooter USB Gamepad",
    price: 56,
    originalPrice: 170,
    rating: 1,
    reviews: 10,
  },
  {
    id: 7,
    image: "/newproducts/product8.png",
    title: "Quilted Satin Jacket",
    price: 100,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
  // headphone
  {
    id: 8,
    image: "/newproducts/gaming/headphone1.png",
    title: "Quilted Satin Jacket",
    price: 100,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
  {
    id: 9,
    image: "/newproducts/gaming/headphone2-removebg-preview.png",
    title: "Bose Headphones",
    price: 100,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
  {
    id: 10,
    image: "/newproducts/gaming/headphone3-removebg-preview.png",
    title: "Uliptz Headphones",
    price: 100,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
  {
    id: 11,
    image: "/newproducts/gaming/headphone4-removebg-preview.png",
    title: "Maxon Headphones",
    price: 100,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
  {
    id: 12,
    image: "/newproducts/gaming/headphone5-removebg-preview.png",
    title: "Sony WH-CH720N White | Wireless Headphones",
    price: 100,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
  {
    id: 13,
    image: "/newproducts/gaming/headphone6-removebg-preview.png",
    title: "Doaqus Gaming Headphones",
    price: 100,
    originalPrice: 1160,
    rating: 3,
    reviews: 28,
  },
//  phones
{
  id: 14,
  image: "/newproducts/phones/phone1.png",
  title: "iPhone 16",
  price: 100,
  originalPrice: 1160,
  rating: 3,
  reviews: 28,
},
{
  id: 15,
  image: "/newproducts/phones/phone2-removebg-preview.png",
  title: "iPhone 15 Pro Max 1 TB",
  price: 100,
  originalPrice: 1160,
  rating: 3,
  reviews: 28,
},
{
  id: 16,
  image: "/newproducts/phones/phone3-removebg-preview.png",
  title: "iPhone 14 Pro Max",
  price: 100,
  originalPrice: 1160,
  rating: 3,
  reviews: 28,
},
{
  id: 17,
  image: "/newproducts/phones/phone4-removebg-preview.png",
  title: "iPhone 12 Pro Max",
  price: 100,
  originalPrice: 1160,
  rating: 3,
  reviews: 28,
},
{
  id: 18,
  image: "/newproducts/phones/phone5.png",
  title: "iPhone 13 Pro Max",
  price: 100,
  originalPrice: 1160,
  rating: 3,
  reviews: 28,
},


  
  // Add more products as needed
];

export default newproductsData;
